.\" x-roff document
.do mso man.tmac
.TH NOTES 1 2021-01-22 "NDC Tools Collection"
.SH NAME
notes - manages note files.
.PP
.SH SYNOPSIS
.SY notes
.OP \-s section
.OP \-a[!][e] name\fR\ \fI\fB[\fIfile\fR\ \fI\fB...][-]\fI
.OP \-a[!]+[e] name\fR\ \fI\fB[\fIfile\fR\ \fI\fB...][-]\fI
.OP \-e[a] \fB{\fIname\fB|\fIpattern\fB}\fI
.OP \-v[a] \fB{\fIname\fB|\fIpattern\fB}\fI
.OP \-p[a] \fB{\fIname\fB|\fIpattern\fB}\fI
.OP \-l \fB[\fIpattern\fB]\fI
.OP \-f pattern
.OP \-d[a] \fB{\fIname\fB|\fIpattern\fB}\fI
.OP \-r old\fB-\fIname\fR\ \fInew\fB-\fIname
.RI [pattern]
.YS
.SH DESCRIPTION
Your notes (files) are stored in a directory (and its subdirectories). This directory can be the \fBNextcloud®\fP's (‘\f[CR]~/Nextcloud/Notes\fP’). The files can be plain text, markdown or anything else that can configured by the \fIrule\fP command in the configuration file (see notesrc(5)). If the \fInote\fP is ‘\f[CR]-\fP’ then it reads from \fIstdin\fP.
.PP
Running program without arguments, enters in TUI mode (ncurses interface).
.PP
The program was designed to behave as the ‘\f[CR]man\fP’ command.
.PP
.RS
.EX
> # show page(s) of section (i.e. subdirectory) 'unix' whose title begins with 'sig11'
> notes -s unix sig11

> # search and show notes for a title with patterns
> notes '*sig*l1*'
.EE
.RE
.SH OPTIONS
.PP
.TP
\fB-a[!], --add[!]
\fRCreates a new note file. If file extension is not specified then it will be used the default (see notesrc). If additional files are specified in the command line, their contents will be inserted into the new note. Use it with ‘\f[CR]-e\fP’ to invoke the editor or ‘\f[CR]-\fP’ to get input from \fIstdin\fP. If the name is already used in this section, then an error will be issued; use ‘\f[CR]!\fP’ option to replace the existing file, or set the clobber variable to ‘\f[CR]false\fP’ in the configuration file.(see notesrc(5))
.PP
.RS
.EX
# example 1: cat yyy zzz > xxx
> notes -a xxx yyy zzz

# example 2:
> cat ~/.notesrc | notes -a! notesrc -
.EE
.RE
.TP
\fB-a[!]+, --append[!]
\fRSame as ‘\f[CR]-a\fP’ but instead of overwriting, the new note is appended to the file. If the name does not exist, then an error will be issued; use ‘\f[CR]!\fP’ option to create it, or set the clobber variable to ‘\f[CR]false\fP’ in the configuration file.(see notesrc(5))
.PP
.TP
\fB-v, --view
\fRShows the \fInote\fP with the default \fI$PAGER\fP if one is not specified in the configuration file.
.PP
.TP
\fB-p, --print
\fRSame as ‘\f[CR]-v\fP’ but writes the contents to \fIstdout\fP.
.PP
.TP
\fB-e, --edit
\fRLoads the \fInote\fP to the default \fI$EDITOR\fP if one is not specified in the configuration file. Also, it can be used with ‘\f[CR]--add/--append\fP’ if it is next to it.
.PP
.TP
\fB-l, --list
\fRDisplays the notes names that match \fIpattern\fP.
.PP
.TP
\fB-f, --files
\fRSame as ‘\f[CR]-l\fP’ but prints out the full path filenames.
.PP
.TP
\fB-d, --delete
\fRDeletes a note.
.PP
.TP
\fB-r, --rename
\fRRenames and/or moves a note. A second parameter is required to specify the new name. If file extension is specified in the new name, then it will use it.\fIrename\fP can also change the section if separated by '/' before the name, e.g.,‘\f[CR]section3/new-name\fP’.
.PP
.TP
\fB-a, --all
\fRDisplays all notes that were found; it works together with ‘\f[CR]-v\fP’,‘\f[CR]-p\fP’,‘\f[CR]-e\fP’, and ‘\f[CR]-d\fP’. Do not use it as first option because it means ‘\f[CR]--add\fP’.
.PP
.TP
\fB-h, --help
\fRDisplays a short help text and exits.
.PP
.TP
\fB--version
\fRDisplays the program version, copyright and license information and exits.
.PP
.TP
\fB--onstart
\fRExecutes the command defined by ‘\f[CR]onstart\fP’ in the configuration file and returns its exit code. This option is useful when custom synchronization is needed.
.PP
.TP
\fB--onexit
\fRExecutes the command defined by ‘\f[CR]onexit\fP’ in the configuration file and returns its exit code. This option is useful when custom synchronization is needed.
.PP
.SH COPYRIGHT
Copyright © 2020-2021 Nicholas Christopoulos.
.PP
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
.PP
.SH AUTHOR
Written by Nicholas Christopoulos <mailto:nereus@freemail.gr>.
.PP
.SH SEE ALSO
\fBnotesrc\fP(5)
,
\fBgroff_man\fP(7)
,
\fBman-pages\fP(7)
.
.PP
